alias: Master Bedroom Fan Control
description: ""
triggers:
  - topic: zigbee2mqtt/Master Bedroom 4-Switch 1/action
    trigger: mqtt
  - topic: zigbee2mqtt/Master Bedroom 4-Switch 2/action
    trigger: mqtt
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '1_single' }}"
        sequence:
          - target:
              entity_id: fan.desk_ceiling_fan
            action: fan.toggle
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '2_single' }}"
        sequence:
          - target:
              entity_id: fan.bed_ceiling_fan
            action: fan.toggle
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '3_single' }}"
        sequence:
          - target:
              entity_id: light.desk_ceiling_fan_down_light
            action: light.toggle
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '3_double' }}"
        sequence:
          - target:
              entity_id: light.desk_ceiling_fan_up_light
            action: light.toggle
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '4_single' }}"
        sequence:
          - target:
              entity_id: light.bed_ceiling_fan_down_light
            action: light.toggle
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '4_double' }}"
        sequence:
          - target:
              entity_id: light.bed_ceiling_fan_up_light
            action: light.toggle
